### ISSUE TITLE
[BUG] The authorization code is invalid on mobile

### ISSUE THREAD

**Issue by SrPeterr** [JakyeRU/Larascord#41]
**Describe the bug**
When trying to log-in on mobile I get this error, but on my computer it works fine

**To Reproduce**
1. Go to my website on my phone
2. Login
2. See error

**Screenshots/Videos**
```
{"larascord_message":"The authorization code is invalid.","message":"HTTP request returned status code 400:\n{\"error\": \"invalid_grant\", \"error_description\": \"Invalid \\\"code\\\" in request.\"}\n","code":400}
```

**Desktop (please complete the following information):**
 - OS: Android 11 MIUI 12.5.1
 - Browser: OperaGX, on desktop works fine.
 - Laravel Version: 9.34.0
 - PHP Version: 8.1.11

**Additional context**
I have disabled adblock and all blocking settings from the app and still the same

**Comment by JakyeRU** [comment]
Hello @SrPeterr,

Thank you for reporting this issue. 

I've tested the authentication on my Android 12 Samsung and it seems to work as expected on Brave, Google Chrome, and Firefox.

I've downloaded OperaGX and got the same error message you got. This issue seems to only happen in OperaGX.

As OperaGX is currently in Early Access and its market share is around 2% I'll be closing this as not planned.
