### ISSUE TITLE
[BUG] Installation stuck or taking an excessive amount of time

### ISSUE THREAD

**Issue by Varga-Levente** [JakyeRU/Larascord#46]
Install stuck here.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/47919682/213666748-24857272-4426-44d9-adc5-603e5cd68976.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Laravel Version: 9.48.0
 - PHP Version: 8.0.25

**Comment by JakyeRU** [comment]
Hello @Varga-Levente,

Thank you for reporting this issue!

It appears that the issue is a result of a recent update to the [laravel/breeze](https://github.com/laravel/breeze/) package.

Prior to this update, when using the command `php artisan breeze:install` without specifying a stack (i.e. blade, vue, react, etc.), it would default to the `blade` stack. However, as per the commit located at https://github.com/laravel/breeze/commit/66a65c5a38ab219da32a00cfa6d10fef162c006e, this feature has been removed.

As such, if no stack is specified, the user will be prompted to make a selection (https://github.com/laravel/breeze/blob/1.x/src/Console/InstallCommand.php#L84). As the [laravel/breeze](https://github.com/laravel/breeze/) package is installed using the -q (quiet) flag, this will prevent the prompt from being displayed, basically pausing the install process forever.

I will be submitting a pull request to address this issue shortly.

**Comment by JakyeRU** [comment]
@Varga-Levente Please try installing the latest version of Larascord. The issue should be fixed now.
